name: Run CI tests

on: [push, pull_request]

jobs:
  build-ubuntu-python-bindings:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2.4.0
    - name: dependencies
      run: sudo apt install python3-pybind11 python3-dev python3-distutils liborc-0.4-dev libvolk2-dev
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_CXX_FLAGS="-Werror" ..
    - name: build
      run: cmake --build build
    - name: test
      run: cd build && ctest -V


  build-ubuntu-full-gnuradio-latest:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2.4.0
    - name: Add GNU Radio PPA
      run: sudo add-apt-repository ppa:gnuradio/gnuradio-releases && sudo apt update
    - name: dependencies
      run: >
        sudo apt install gnuradio python3-uhd python3-pybind11 liborc-0.4-dev
        libspdlog-dev libsndfile1-dev
        && sudo pip3 install pygccxml pyqtgraph
    - name: Print configuration
      run: |
        uname -a
        gnuradio-config-info --print-all
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_CXX_FLAGS="-Werror" ..
    - name: build
      run: cmake --build build
    - name: test
      run: cd build && ctest -V

  build-ubuntu-full-gnuradio-39:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2.4.0
    - name: Add GNU Radio PPA
      run: sudo add-apt-repository ppa:gnuradio/gnuradio-releases-3.9 && sudo apt update
    - name: dependencies
      run: >
        sudo apt install gnuradio python3-uhd python3-pybind11 liborc-0.4-dev
        libfmt-dev libsndfile1-dev
        && sudo pip3 install pygccxml pyqtgraph
    - name: Print configuration
      run: |
        uname -a
        gnuradio-config-info --print-all
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_CXX_FLAGS="-Werror" ..
    - name: build
      run: cmake --build build
    - name: test
      run: cd build && ctest -V
